github: [elynx]
custom: ["https://yoomoney.ru/quickpay/shop-widget?writer=buyer&targets=&targets-hint=За%20моды%20для%20Зумов&default-sum=100&button-text=13&payment-type-choice=on&hint=&successURL=&quickpay=shop&account=4100117541059887"]
